# CONFIGURAZIONE DATABASE POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bugboard
spring.datasource.username=postgres
spring.datasource.password=123456

# CONFIGURAZIONE HIBERNATE (JPA)
# "update" dice a Spring di creare o aggiornare automaticamente le tabelle nel DB partendo dalle tue classi Java
spring.jpa.hibernate.ddl-auto=update

# Mostra le query SQL nel terminale (utilissimo per il debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disabilita un controllo di sicurezza di default di Spring Security per poter testare le API più facilmente all'inizio
spring.security.user.name=user
spring.security.user.password=password